### ISSUE TITLE
did the site get taken down? 

### ISSUE THREAD

**Issue by DentyMods** [Nekos-life/nekos-dot-life#11]

**Comment by xXBuilderBXx** [comment]
The host for the API is having issues atm apparently a fibre cable got cut. If you want more info or news when it's back online join the Discord support server https://discord.gg/r4Ju6TJ

**Comment by DentyMods** [comment]
ok thanks

**Comment by xXBuilderBXx** [comment]
The API is back on now you can close this issue ;)
