### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by fluffyloopy** [Nekos-life/nekos-dot-life#12]
How do i use commands on discord bots? idk how to make stuff like 
```const client = require('nekos.life');
const {sfw} = new client();
 
sfw.neko().then(neko => console.log(neko));
```
on discord. it keeps saying "invalid body form" and that its not a string. how do i use it?

**Comment by TheCyberRonin** [comment]
You'll have to give me a bit more info/code there. In what context are you trying to use this?
And as you'll see in the documentation, that `neko` would then be an object with `url` as a property and that would be the link to an image:
```js
{ url: 'https://cdn.nekos.life/neko/neko_083.jpg' }
```

**Comment by fluffyloopy** [comment]
im just trying to use it on a bot which i cant figure out how to make it work. I've tried using it like these two ways tho... it failed. took me a while to realise it doesnt work as simple as just embedding a link. so how do i accomplish this using nekos life module? as in, make them appear in discord embeds as gifs/pics.

```
if (cmd == "neko") {
            nsfw.neko().then (neko => msg.edit(neko));
```
```
    if (cmd === "neko") {
        nsfw.neko().then(neko => {
                msg.edit("", { embed: new Discord.RichEmbed().setTitle("").setColor("#FBFF00").setImage(neko).setFooter("Image by nekos.life") })
            })
      }

```

**Comment by PantherMlem** [comment]
It seems this issue is more to do with how to write the code for a discord bot? Here's an example which should help you:

```
    const nekojson = await neko.sfw.meow();

    const exEmbed = new Discord.RichEmbed()
	        .setTitle('Dark Fear Bot - Gifs Powered by Nekos.life')
	        .setDescription('Hey look, a cute kitty!')
    	.setImage(nekojson['url'])
    	
        message.channel.send(exEmbed)
```

**Comment by IamTails** [comment]
This is a conversation better suited to our API support channel in the official discord, which can be found here https://discord.gg/2wcb8wZ
