### ISSUE TITLE
API (and website as a whole) is down

### ISSUE THREAD

**Issue by sks316** [Nekos-life/nekos-dot-life#13]
**Describe the bug**
Read the title.

**To Reproduce**
1. Go to nekos.life
2. See error
3. Panic internally

**Expected behavior**
Uh, not an error?

**Comment by zThana** [comment]
The server the Nekos.life website & API is being hosted on was temporarily down due to a hardware-related issue.
The server is back online but the API is still having some difficulties.

It'll be back up soon.

**Comment by xXBuilderBXx** [comment]
The API is back online now, you can close this issue.
