### ISSUE TITLE
Duplicate in endpoint.json

### ISSUE THREAD

**Issue by Swyreee** [Nekos-life/nekos-dot-life#15]
2 endpoints in endpoints.json are the same: [here](https://github.com/Nekos-life/nekos-dot-life/blob/master/endpoints.json#L4) and [here](https://github.com/Nekos-life/nekos-dot-life/blob/master/endpoints.json#L41).

I don't know if this is on-purpose or not

**Comment by SpeckyYT** [comment]
It looks to be on purpose, because both endpoints [pussy and pussyGif] return a GIF.

**Comment by TheCyberRonin** [comment]
PR that was merged should have resolved this.
