### ISSUE TITLE
Add sfw.chat back again

### ISSUE THREAD

**Issue by AlonsoAliaga** [Nekos-life/nekos-dot-life#19]
**Describe new features you want**
chat function was removed.

**Describe the solution you'd like**
add it back

**Describe alternatives you've considered**
none

**Additional context**
none

**A Gif to describe how you feel when you made this request**
none

**Comment by IamTails** [comment]
The chat function in theory was an amazing thing that continuously learned from whatever conversations that it was having globaly 

In practice it was a nightmare all of that learning essentially continuously turned it into a toxic cancerous mildly retarded chatbot so I considered it a failed experiment and removed it

Going forward if it were to ever be added back I would have to have an extremely large dataset for training that didn't evolving learning from the general public and I honestly just don't have the time or motivation to do it if you or anybody else reading this in the future has a large dataset and wants to spend the hours training a model I will gladly use your model and re-add it
