### ISSUE TITLE
Unresponsive Commands

### ISSUE THREAD

**Issue by Mee6s** [Nekos-life/nekos-dot-life#24]
**Describe the bug**
I don't know why but any command I use involving a nekos.life command won't work when I am hosting my .js bot on my linux machine. (Linux Mint). I have npm, nodejs, etc. on it already and everything works fine with other bots.

**To Reproduce**
Steps to reproduce the behavior: Have Linux mint on your laptop or computer, have 
Nodejs, and npm installed then either git clone from github or copy and paste folder from thumb drive to computer. Then start up the bot using terminal window/shell.

**Expected behavior**
All commands to work fine like they do on my windows laptop. (What I get is all my other commands work, except the nekos.life commands)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Node version: v12.17.0

**Additional context**
The bot you can see here is online.

![IMG_20200529_121542](https://user-images.githubusercontent.com/45724082/83291931-7bb00e00-a1a6-11ea-83fa-7d7f04b27ae3.jpg)
![unknown2](https://user-images.githubusercontent.com/45724082/83292001-9bdfcd00-a1a6-11ea-840e-471a95e53a71.png)

When Commands are entered, No response. (Other commands like, help, and whois, work just fine.
![unknown](https://user-images.githubusercontent.com/45724082/83292048-b0bc6080-a1a6-11ea-8868-4a90070dff20.png)

As you can see here.
![unknown3](https://user-images.githubusercontent.com/45724082/83292352-30e2c600-a1a7-11ea-8335-e73bb07384a9.png)

**Notes**
The bot and the nekos.life commands work functionally well when hosted on my widows 10 laptop. The files used in both folders are identical except the .bat file to start it is now a .sh but the code in the files are the same.

**Comment by TheCyberRonin** [comment]
I don't believe you being on Linux or not should have any effect on if the commands work or not. Could you provide more details or examples of your commands or log what you get to console when you try to access the API using the library?

**Comment by Mee6s** [comment]
> 
> 
> You being on Linux should have no effect on the library operating. Could you please provide more details or examples of your commands or log what you get to console when you try to access the API using the library?

I get nothing when using commands and accessing the API/library, No errors, no warnings, nothing. Even when I try to Debug, I get nothing.

I just get "{username} used the +{name of command here} command" sent to my log when someone issues the command in the server. Other than that. Nothing. Just says the command was used and no result in the discord channel. (Hosted On windows 10, it actually sends the embed to the discord channel).

If I provide pictures, or a copy&paste of my log, you'd see nothing like I see. (you'd see the previous picture above with my log/Terminal)

This is the code I use for pretty much everything else involving nekos.life API, just a basic embed with the api link there to post the content/picture in the embed. Ecept for the NSFW stuff, I have a nsfw channel check ontop of the normal embed stuff.
![Annotation 2020-05-29 161722](https://user-images.githubusercontent.com/45724082/83309988-f0477480-a1c7-11ea-845c-8da4045f076f.jpg)


Everything else works correctly with my bot, even other commands with embeds. Just not the commands that have Nekos.life api related to them. I've checked and double checked to make sure I have all the node modules I need for my bot to work and I have everything. So I am clueless as to why the commands don't work when I host the bot on my Linux Computer but work fine when hosted on my windows 10 computer.

**Comment by TheCyberRonin** [comment]
Oh it seems that you're not using the library that this repo is for. This repo is for the nekos.life NPM library. Not the actual API itself.

**Comment by TheCyberRonin** [comment]
But I can still try to help you out with this. Could you please `console.log` your `response` to see what you got. You also aren't error checking at all with the API call.

**Comment by Mee6s** [comment]
> 
> 
> But I can still try to help you out with this. Could you please `console.log` your `response` to see what you got. You also aren't error checking at all with the API call.

Huh, I used `npm i -s nekos.life` as shown in the readme file here in this repo. didn't know they were different. Anyways I will send you the response I get in my terminal/log after issuing a command.

**Before**
![IMG_20200529_165301](https://user-images.githubusercontent.com/45724082/83311718-45d25000-a1cd-11ea-8657-65b6ff2280d9.jpg)


**After**
![IMG_20200529_165315](https://user-images.githubusercontent.com/45724082/83311739-597db680-a1cd-11ea-8fab-aa52b31383a0.jpg)

**Discord Chat**
![unknown](https://user-images.githubusercontent.com/45724082/83311787-7dd99300-a1cd-11ea-952f-9b1b2015ad83.png)


That is my console log response. As you can see, nothing in the chat, just the command. No embed, nothing.

**Comment by TheCyberRonin** [comment]
You are not logging the response. You are literally using `console.log("<username> used <command>")`.... And like I said you should be logging the errors. 

Also, you may have installed the module, but you aren't using it like the examples in the README, you're using superagent to call directly to the API. I believe you don't really know exactly what you're doing.

If you want to see the response from the API, you should be doing `console.log(response)` instead of that string. I'm almost certain you're either having an error in the superagent call or your code is having some sort of race condition.

**Comment by Mee6s** [comment]
putting console.log(response) in place of console.log("<username> used <command>") and running the command does nothing but say "response is not defined"

**Comment by TheCyberRonin** [comment]
Please join the Discord and ping me (CyberRonin) and I'll give you direct help to resolve it. I think you have some things in the wrong order.

https://discord.gg/ETrVFS
