### ISSUE TITLE
question

### ISSUE THREAD

**Issue by TogamiCookiie** [Nekos-life/nekos-dot-life#28]
for any usage of this wrapper, i need to request via async? thanks.

**Comment by TheCyberRonin** [comment]
What exactly are you asking? The wrapper is async by nature. You can use promises or async/await.

**Comment by TogamiCookiie** [comment]
In my exports.run, do I specify async before Passing the params.

**Comment by TheCyberRonin** [comment]
Bruh, can you join the Discord and ping CyberRonin for help?? It'd probably be better to share some code so you can show me what you mean. I'm sure I can help you figure it out .

https://discord.gg/skkUsp

**Comment by TogamiCookiie** [comment]
Good morning Nekos-life/nekos-dot-life.

Yeah, I’ll join when I cook breakfast and brew coffee.

Thanks.

**Comment by TogamiCookiie** [comment]
[![https://i.vgy.me/k2VjjG.png](https://i.vgy.me/k2VjjG.png)

**Comment by xXBuilderBXx** [comment]
@TogamiCookiie use https://discord.gg/gwEF4X

**Comment by TheCyberRonin** [comment]
Thanks, Builder. The invite I posted expired after 24 hours so there wasn't a random unlimited link out there.

But yeah, please ping me when you get into the server in the #api-support channel so I can help you out.
