### ISSUE TITLE
Create an issue template

### ISSUE THREAD

**Issue by TheCyberRonin** [Nekos-life/nekos-dot-life#3]
Create a typical issue template with a section for a description of the issue, expected result, and how to repeat the issue.

**Comment by cfanoulis** [comment]
May I ask to claim this?

**Comment by TheCyberRonin** [comment]
Sure, have at it! Thanks for doing so!!

**Comment by TheCyberRonin** [comment]
You can just close the issue with the PR then.

**Comment by cfanoulis** [comment]
👍 Working on it, the PR should be up in around 24hrs

Χαράλαμπος Φανούλης
Μαθητής 4ου Γυμνασίου Ευόσμου

**Comment by cfanoulis** [comment]
Tadaa https://github.com/Nekos-life/nekos-dot-life/pull/7
