### ISSUE TITLE
Make it just send the link like nekos.py instead of a json

### ISSUE THREAD

**Issue by S4qib** [Nekos-life/nekos-dot-life#31]
Make it just send the link like nekos.py instead of a json

**Comment by xXBuilderBXx** [comment]
Not really an issue since every lang can parse json easily and if you can't do that then good luck trying to use any other apis that use that standard.

**Comment by xXBuilderBXx** [comment]
Also you can get the url doing
neko.nsfw.neko().then(neko => {console.log(neko.url);});

**Comment by TheCyberRonin** [comment]
You could also do something as simple as
```js
neko.sfw.hug().then({url} =>{
  console.log(url);
})
```

**Comment by TheCyberRonin** [comment]
Also closing this as it is a non-issue with the library.
