### ISSUE TITLE
Slow promise

### ISSUE THREAD

**Issue by sinkaroid** [Nekos-life/nekos-dot-life#32]
**Slow promise**
Sometime i getting slow promise when fetch any nekos through this wrapper,   
but when i fetched manual with node-fetch example: https://www.nekos.life/api/v2/img/wallpaper  
with node-fetch the image return is fast properly, also i'm not using any kind of delay function.  

**Desktop**
 - Node version 14.5.0  

Ty sir

**Comment by TheCyberRonin** [comment]
Does it happen consistently? Like every single API call using this wrapper, every single time?

**Comment by IamTails** [comment]
If this isn't reproducible, it's a fair bet based on the timeframe this was likely caused by me moving core services to new hardware which was causing widespread delays and instability and should be resolved now

**Comment by sinkaroid** [comment]
ah i see and yes it's not slow anymore, also me just happened to implement a sharding right now
thx for your beautiful api
