### ISSUE TITLE
The wallpaper endpoint is NSFW

### ISSUE THREAD

**Issue by t41y0u** [Nekos-life/nekos-dot-life#33]
The wallpaper endpoint has several pictures that aren't SFW.
Examples: https://cdn.nekos.life/wallpaper/Yk22OErU8eg.png, https://cdn.nekos.life/wallpaper/dvGFI8aD_og.jpg, https://cdn.nekos.life/wallpaper/Bwt-fdzTGRU.jpg, https://cdn.nekos.life/wallpaper/QWs7Um5XVnY.png

**Comment by TheCyberRonin** [comment]
This repo is for the library itself, not the API. For future reference, please report the images on the Discord server!

**Comment by t41y0u** [comment]
Where can I find the Discord server?

**Comment by Cheeziess** [comment]
top right corner at https://nekos.life/
