### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xyz-Yanys** [Nekos-life/nekos-dot-life#35]
I recently tried to add NSFW commands to my bot using this library, but I get this error:
`TypeError: client is not a constructor`.
where my code is:
`const Discord = require('discord.js')
const client = new Discord.Client()
const config = require('./config.json')
const command = require('./command')
const poll = require('./poll')
const memberCount = require('./memberCount')
const fs = require("fs");
const hentai = require('./hentai')
const neko = require('nekos.life')
const neki = new client();`

what should I do to resolve this problem?

**Comment by TheCyberRonin** [comment]
You should take a look at the Readme to see how to properly use the library. It seems as though you have not done so, or do not understand JS that well.
