### ISSUE TITLE
.sfw.wallpaper() also returns nsfw wallpapers

### ISSUE THREAD

**Issue by Aw4k3** [Nekos-life/nekos-dot-life#36]
I am using this in a discord bot and despite the `wallpaper()` method being in the `sfw` property, it still has a chance of returning a nsfw wallpaper.

Here is the code block where I am using this
```js
case '-wallpaper':
    NekoClient.sfw.wallpaper().then(image => {
        console.log(Utils.getTimeStamp() + 'Fetched url ' + image.url);
        NekoEmbed.setDescription('Wallpaper');
        NekoEmbed.setImage(image.url);
    }).then(fuckyoujavascript => {
        msg.channel.send(NekoEmbed);
    });
    break;
```

**Comment by moyshik7** [comment]
Same here
It almost got my Discord bot banned.
Also I wonder why nekos.life is still alive after having 100 reports a day for providing nsfw image of minors

**Comment by Hatsune-Mikun** [comment]
Better use [this library](https://www.npmjs.com/package/hmfull), this one includes more sources, and checking all endpoints more time to choose category, so this one more safe

**Comment by Hatsune-Mikun** [comment]
@Aw4k3 @moyshik7 

Better use [this library](https://www.npmjs.com/package/hmfull), this one includes more sources, and checking all endpoints more time to choose category, so this one more safe
