### ISSUE TITLE
8Ball doesn't work, well atleast using traditional method.

### ISSUE THREAD

**Issue by dimactavishy** [Nekos-life/nekos-dot-life#37]
Adding `8Ball` will always result in a problem saying:
An identifier or keyword cannot immediately follow a numeric literal.

The problem is as simple as replacing any neko.sfw.<stuff> with neko.sfw.8Ball

Perhaps i was just doing it wrong? All i did was just copy the example and replace the stuff with 8Ball. It should've worked because i already got a dozen working .js files that uses the same method.

 - OS: Windows 10
 - Node version v16.11.1

Note: Discord.js

**Comment by TheCyberRonin** [comment]
What's the code look like that you're using and what version of Node?

**Comment by TheCyberRonin** [comment]
Fixed this in the latest release.
