### ISSUE TITLE
Anime Roleplay commands won't work.

### ISSUE THREAD

**Issue by DeltaCoderr** [Nekos-life/nekos-dot-life#38]
Anime Roleplay commands such as hug, pat, kiss, baka etc aren't working since Yesterday.

And whenever someone uses the command, the bot throws this error.

``Error: connect ECONNREFUSED 0.0.0.0:443``

![image](https://user-images.githubusercontent.com/51528076/144743950-cfeac0f1-4da1-4a33-8ced-e2eb968ee6d2.png)

I don't know if this is an issue with the API itself. Since I didn't change my code and it's working perfectly fine.

**Comment by Abadima** [comment]
Same thing here, it seems to be an ongoing situation.

**Comment by TheCyberRonin** [comment]
I'll take a look and update the library if need be. Hopefully I'll at least find a solution if the library isn't broken as well.

**Comment by TheCyberRonin** [comment]
Tried the library on LTS and current Node versions and it works fine. It may be repl.it that's having the mess up. 

The error that was reported seems to be a DNS or network related issue with the VPS or the host.
