### ISSUE TITLE
Bug report: I get ECONNREFUSED when I request from my app

### ISSUE THREAD

**Issue by PuneetGopinath** [Nekos-life/nekos-dot-life#39]
**Describe the bug**
I am not sure if this is a bug, but when I request from my app (discord bot) it gives me error `Error: connect ECONNREFUSED 0.0.0.0:443`
But when I open the same url in my browser it works, so I doubt if this is a bug

**To Reproduce**

Request to any endpoint of the nekos.life api v2 with nodejs + axios

Sample Code:
```js
require("axios")({ method: "get", url: "https://nekos.life/api/v2/img/tickle" }).then(data => console.log(data.res)).catch(err => console.log(err));
```

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux
 - Node version [node -v] v16.13.0

**Additional context**
Also I didn't use this wrapper I just used the main api directly, I found this as the official wrapper so I came to report here
Let me know if you want me to try with this wrapper

Thanks in advance

**Comment by IamTails** [comment]
sounds like you are usually replit, please see
https://blog.replit.com/family-friendly-dns

**Comment by PuneetGopinath** [comment]
Ohk, I will switch my host then
Thanks
