### ISSUE TITLE
Create a feature request template

### ISSUE THREAD

**Issue by TheCyberRonin** [Nekos-life/nekos-dot-life#4]
Please create a feature request template. A good one might contain a good description of the feature like a function and an example output of it as well as why it would be a good feature to add.

**Comment by Nirajn2311** [comment]
Can I take this up?

**Comment by TheCyberRonin** [comment]
Sounds great, thanks for the interest! Just go ahead and close the issue with the PR.

**Comment by Nirajn2311** [comment]
I can also make a template for bugs and issues.

**Comment by TheCyberRonin** [comment]
Go for it

**Comment by TheCyberRonin** [comment]
well, the issue template is for another issue that someone else claimed
