### ISSUE TITLE
Divide the NSFW and SFW functions a bit more

### ISSUE THREAD

**Issue by Alcha** [Nekos-life/nekos-dot-life#9]
**Describe new features you want**
Currently, all of the available endpoints are exposed via the `NekoClient` class as individual functions. It would be great if you could instantiate the module but say you only want the SFW functions at the moment.

**Describe the solution you'd like**
The `NekoClient` class constructor would have one optional parameter `contentType`. If undefined, it would assign all functions as usual so it's still backward compatible.

If `contentType` is **SFW** or **NSFW**, then only assign those functions to the class.

**Describe alternatives you've considered**
At first, I thought it would be easier to just export a **SFW** and **NSFW** object in the `NekoClient` class that you could choose. After tinkering with it some more I realized this would break backward compatibility as any previous code relying on the function calls would then have to add a `sfw` or `nsfw` prefix to the function call.

**Additional context**
I've created a working version of this on [my fork][0], but I'm not entirely sure how to show this new conditional function stuff in TypeScript. So at the moment, when you install my fork it still shows all of the functions exported as usual no matter what.

However, if you do something like the following, you'll get a function not found error:
```javascript
const Neko = require('nekos.life')
const neko = new Neko('sfw')

neko.getNSFWBoobs()
  .then(res => console.log(res.url))
  .catch(err => console.error(err))
```

**A Gif to describe how you feel when you made this request**
![LWA][1]

[0]: https://github.com/Alcha/nekos-dot-life
[1]: https://media1.tenor.com/images/2c8de031f56a1b270ae18a2043078aa6/tenor.gif?itemid=5226558

**Comment by TheCyberRonin** [comment]
What I could possibly do is separate them altogether and make it a full release to get ready for V3 of the API.

The idea that I have would be to import sfw and nsfw either all at once or separately instead of everything by default. It would look something like this:
```js
const NekoClient = require('nekos.life');
const {sfw} = new NekoClient();

sfw.hug
  .then(res => console.log(res.url))
  .catch(err => console.log(err));
```

What are your thoughts on something like this?

**Comment by Alcha** [comment]
I didn't know there was a V3 in the works, I just found out about **nekos.life** last night/this morning. This is great to hear!

As for the splitting of functions, I love your implementation more than mine. Being able to call the `SFW` functions like that would be wonderful. 

If there's any way in which I can help, I'd be more than happy to. I noticed we have different code style preferences but I can always work around whatever is currently set, I'd love to be able to help out as I intend on using this module in [my Discord bot][0].

[0]: https://github.com/HF-Solutions/Tron

**Comment by TheCyberRonin** [comment]
I'll probably take a better look and update sometime in the next week. The only unfortunate thing about doing so is that it will be a breaking change. It's okay that it's a breaking change because with V3 of the API coming, it would have to be a breaking change either way.

**Comment by Alcha** [comment]
You could go with the changes I have in my fork of the repo for the time being. It's not a breaking change and it still supports separating of the two groups of functions.

Then when the V3 API comes out, you could submit the breaking change that coincides with the API changes.

**Comment by TheCyberRonin** [comment]
I think I actually really like the newer changes. I will probably update the lib this weekend along with a new README to show the new changes. It looks so much more clean. ![image](https://app.gitkraken.com/api/glo/boards/5c07c822e5457c002eb5c8b8/attachments/5c07db76e5457c002eb5d7c9)

**Comment by TheCyberRonin** [comment]
Take a look at the npm page 😉

**Comment by Alcha** [comment]
Me right now:

![YASS][0]

Thank you so much!

[0]: https://media1.tenor.com/images/d5dd32a2b0dfa0c5fb069989033bac45/tenor.gif?itemid=12962363
